apiVersion: v1
kind: Service
metadata:
  name: wil423
  labels:
    app: wil423
spec:
  type: NodePort 
  ports:
  - name: http
    port: 80
    targetPort: 8888
  selector:
    app: wil423
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil423
spec:
  selector:
    matchLabels:
      app: wil423
  replicas: 1
  template:
    metadata:
      labels:
        app: wil423
    spec:
      containers:
      - name: wil423
        image: wil423/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wil423
                port:
                  name: http
